// Generated by tools/generate_abvm_abi.py. Do not edit.
using System.Runtime.InteropServices;

namespace Ams.UI.Services;

internal static class AbvmAbi
{
    public const string Magic = "ABP1";
    public const int FormatVersion = 2;
    public const int VmAbi = 1;
    public const int HeaderSize = 128;
    public const int InstructionSize = 16;
    public const int RouteSize = 16;
    public const int ResourceCertificateSize =
        36;
}

internal enum AbvmOpcode : byte
{
    END = 0,
    DELAY = 1,
    KEY = 2,
    KDOWN = 3,
    KUP = 4,
    TYPE = 5,
    RMOUSE = 6,
    BEEP = 7,
    LOOP_ENTER = 10,
    LOOP_NEXT = 11,
    RPKG_ENTER = 12,
    ITEM_END = 13,
    SCOPE_BEGIN = 20,
    LANE_END = 21,
    WATCH = 22,
    JUMP = 30,
}

internal enum AbvmConstantKind : byte
{
    UTF8 = 1,
    TYPE = 2,
    MOUSE = 3,
    RANGES = 4,
    SCOPE = 5,
    SOUND = 6,
    LIGHT = 7,
    GUARD = 8,
    CYCLE = 9,
}

internal enum AbvmScopePolicy : byte
{
    JOIN_ALL = 1,
    CANCEL_ON_ANY = 2,
    CANCEL_ON_TERMINAL_LANE = 3,
    KEEP_RUNNING_UNTIL_CANCELLED = 4,
}

internal enum AbvmRoutePolicy : byte
{
    DENY = 0,
    ABORT_AND_START = 1,
    INTERRUPT_AND_RESUME = 2,
    CANCEL_SCOPE_AND_CONTINUE = 3,
    ABORT_AND_RESTART = 4,
}

internal enum AbvmRouteClockPolicy : ushort
{
    WALL = 0,
    ACTIVE = 256,
}

[System.Flags]
internal enum AbvmRouteFlag : ushort
{
    PAUSE_RELEASE_HID = 512,
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmHeader
{
    public uint Magic;
    public ushort FormatVersion;
    public ushort VmAbi;
    public uint Flags;
    public uint FileSize;
    public uint HeaderSize;
    public uint CodeOffset;
    public uint CodeCount;
    public uint ConstantOffset;
    public uint ConstantSize;
    public uint RouteOffset;
    public uint RouteCount;
    public uint ResourceOffset;
    public uint ResourceSize;
    public uint Crc32;
    public ushort MaxFrames;
    public ushort MaxLanes;
    public ulong SourceSha0;
    public ulong SourceSha1;
    public ulong SourceSha2;
    public ulong SourceSha3;
    public ulong ProgramSha0;
    public ulong ProgramSha1;
    public ulong ProgramSha2;
    public ulong ProgramSha3;
    public uint Reserved;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmInstruction
{
    public byte Opcode;
    public byte Flags;
    public ushort OperandA;
    public uint OperandB;
    public uint OperandC;
    public uint OperandD;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmRoute
{
    public ushort RouteId;
    public ushort PolicyFlags;
    public uint Pc;
    public uint Length;
    public uint NameConstant;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmResourceCertificate
{
    public ushort Version;
    public ushort Size;
    public ushort MaxFrames;
    public ushort MaxLanes;
    public ushort MaxActors;
    public ushort MaxEvents;
    public ushort MaxInterrupts;
    public ushort SoundProfiles;
    public ushort SoundListeners;
    public ushort PwmChannels;
    public uint MaxConstantBytes;
    public uint MaxTypeBytes;
    public uint MaxMouseBytes;
    public uint Capabilities;
}
