using Ams.UI.Models;

namespace Ams.UI.Services;

/// <summary>
/// Emits a self-contained PowerShell runner (the script includes a minimal bridge
/// client — the user only needs bridge.py + the python folder next to it).
/// Board command syntax verified against firmware 1.6 (pipe separator, §15.5).
/// Long-window commands (WSND/TRGSND) get a proportional timeout (§15.4 rule 4).
/// Sensitive typeText steps go via clipboard and carry a plain-text warning comment.
/// </summary>
public static class ScriptGenerator
{
    public static void Generate(string path, IEnumerable<StepNode> roots, string port, string pythonDir,
                                int mouseSpeedMin = 0, int mouseSpeedMax = 2300,
                                int screenW = 1920, int screenH = 1080)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("#Requires -Version 5.1");
        sb.AppendLine("<#");
        sb.AppendLine("  Generated by Classroom Studio — " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
        sb.AppendLine("  Requires: python + pyserial on PATH, the AMS 'pc' folder (ams_serial.py/ams_crypto.py),");
        sb.AppendLine("  and bridge.py next to this script (copy it from the AMS app folder).");
        sb.AppendLine("#>");
        sb.AppendLine("param(");
        sb.AppendLine("    [string]$Port = '" + port.Replace("'", "''") + "',");
        sb.AppendLine("    [string]$PythonDir = '" + pythonDir.Replace("'", "''") + "'");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("Set-StrictMode -Version Latest");
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();
        sb.AppendLine(EmitHeader());

        sb.AppendLine("try {");
        sb.AppendLine("    Start-Board");
        sb.AppendLine("    Send-Cmd \"SETRES|$([System.Windows.Forms.SystemInformation]::PrimaryMonitorSize.Width),$([System.Windows.Forms.SystemInformation]::PrimaryMonitorSize.Height)\"");
        sb.AppendLine();

        foreach (var n in roots) EmitStep(sb, n, 1, mouseSpeedMin, mouseSpeedMax, screenW, screenH);

        sb.AppendLine("}");
        sb.AppendLine("finally {");
        sb.AppendLine("    try { Send-Cmd 'HALT' } catch { }   # guaranteed key/button release (§10.3 rule 8)");
        sb.AppendLine("    try { __Send-Raw (@{ op = 'disconnect' }) } catch { }");
        sb.AppendLine("    if ($script:br) { try { $script:br.StandardInput.Close(); $script:br.WaitForExit(3000) } catch { $script:br.Kill() } }");
        sb.AppendLine("}");

        // UTF-8 WITH BOM — Windows PowerShell 5.1 reads BOM-less UTF-8 as ANSI (field bug #2)
        System.IO.File.WriteAllText(path, sb.ToString(), new System.Text.UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    private static void EmitStep(System.Text.StringBuilder sb, StepNode n, int depth,
                                  int mouseSpeedMin = 0, int mouseSpeedMax = 2300,
                                  int screenW = 1920, int screenH = 1080)
    {
        string pad = new(' ', depth * 4);
        if (n.IsDisabled)
        {
            sb.AppendLine(pad + "# DISABLED: " + n.Summary.Replace('\n', ' '));
            return;
        }

        sb.AppendLine(pad + "# --- " + (string.IsNullOrWhiteSpace(n.Name) ? n.Summary : n.Name + " — " + n.Summary));

        switch (n.Type)
        {
            case "delay":
            {
                int min = PropEx.GetInt(n.Props, "minMs"), max = PropEx.GetInt(n.Props, "maxMs", 333);
                if (max < min) (min, max) = (max, min);
                sb.AppendLine(max <= min ? $"{pad}Start-Sleep -Milliseconds {min}" : $"{pad}Start-Sleep -Milliseconds (Get-Random -Minimum {min} -Maximum {max + 1})");
                break;
            }
            case "forLoop":
            {
                string v = "$__i" + depth, t = "$__t" + depth;
                switch (PropEx.GetString(n.Props, "mode", "count"))
                {
                    case "count":
                        sb.AppendLine($"{pad}for ({v} = 1; {v} -le {Math.Max(0, PropEx.GetInt(n.Props, "count", 10))}; {v}++) {{");
                        break;
                    case "time":
                    {
                        long ms = PropEx.GetInt(n.Props, "timeValue", 10) * UnitMs(PropEx.GetString(n.Props, "timeUnit", "minute"));
                        sb.AppendLine($"{pad}{t} = [Diagnostics.Stopwatch]::StartNew()");
                        sb.AppendLine($"{pad}while ({t}.ElapsedMilliseconds -lt {ms}) {{");
                        break;
                    }
                    default:
                        sb.AppendLine($"{pad}while ($true) {{");
                        break;
                }
                foreach (var c in n.Children) EmitStep(sb, c, depth + 1, mouseSpeedMin, mouseSpeedMax, screenW, screenH);
                sb.AppendLine(pad + "}");
                break;
            }
            case "randomPackage":
                sb.AppendLine(pad + "# TODO: Random Package — run this script via the AMS app's Run (per-pass shuffle/subset is app-side, v0.7.8)");
                break;

            case "parallelGroup":
                sb.AppendLine(pad + "# PARALLEL GROUP — NOTE: this generated script runs the children SEQUENTIALLY.");
                sb.AppendLine(pad + "# True concurrent typing+mouse needs the Classroom Studio app's Run (one serial channel, app-paced interleave).");
                foreach (var c in n.Children) EmitStep(sb, c, depth + 1, mouseSpeedMin, mouseSpeedMax, screenW, screenH);
                break;

            case "label":
                sb.AppendLine(pad + "# ==== label: " + PropEx.GetString(n.Props, "label") + " ====");
                break;

            case "gotoLabel":
                sb.AppendLine(pad + "# TODO: Go To Label '" + PropEx.GetString(n.Props, "label") + "' — run via the AMS app (goto is app-side, v0.8.3)");
                break;

            case "comment":
                foreach (var line in PropEx.GetString(n.Props, "text").Replace("\r\n", "\n").Split('\n'))
                    sb.AppendLine(pad + "# " + line);
                break;

            case "waitForLight":
            {
                int lightTimeoutMs = PropEx.GetInt(n.Props, "timeoutMs", 20000);
                double lightTimeoutSec = lightTimeoutMs / 1000.0 + 10;   // window + overhead (§15.4 rule 4)
                sb.AppendLine($"{pad}Send-Cmd \"{StepDefinitions.GetCommands(n)[0]}\" -TimeoutSec {lightTimeoutSec:0}");
                break;
            }

            case "waitForSound":
            {
                int timeoutMs = PropEx.GetInt(n.Props, "timeoutMs", 20000);
                double timeoutSec = timeoutMs / 1000.0 + 10;   // window + overhead (§15.4 rule 4)
                sb.AppendLine($"{pad}Send-Cmd \"{StepDefinitions.GetCommands(n)[0]}\" -TimeoutSec {timeoutSec:0}");
                break;
            }

            case "openFile":
            {
                var ofp = PropEx.GetString(n.Props, "path");
                var ofa = PropEx.GetString(n.Props, "args");
                var ofw = PropEx.GetString(n.Props, "windowState", "normal") switch
                {
                    "maximized" => " -WindowStyle Maximized",
                    "minimized" => " -WindowStyle Minimized",
                    _ => "",
                };
                sb.AppendLine($"{pad}Start-Process -FilePath '{ofp.Replace("'", "''")}'" +
                              (ofa.Length > 0 ? $" -ArgumentList '{ofa.Replace("'", "''")}'" : "") + ofw);
                break;
            }

            case "playScript":
                sb.AppendLine(pad + "# playScript: run the target .amk via the AMS app (it decodes + runs recursively) — not inlined here");
                break;

            case "findImage":
                sb.AppendLine(pad + "# TODO: PC-side image search — run this script via the AMS app's Run for Find Image support");
                break;

            case "randomMousePosition":
            {
                var (x, y, w, h) = (PropEx.GetInt(n.Props, "x"), PropEx.GetInt(n.Props, "y"),
                                    Math.Max(1, PropEx.GetInt(n.Props, "w", 100)), Math.Max(1, PropEx.GetInt(n.Props, "h", 100)));
                // v0.9.0 — delegate to the human-mouse engine (WindMouse path from the REAL cursor
                // position, ease-in-out timing, overshoot & correct, full pause manager).
                // The old inline block curved from the region's corner (wrong origin), used
                // [Math]::Random::Default.NextDouble() (does not exist — crashes PowerShell 5.1)
                // and emitted six closing braces for one block (the script failed to parse).
                sb.AppendLine($"{pad}$destX = {x} + $script:rng.Next(0, {w})");
                sb.AppendLine($"{pad}$destY = {y} + $script:rng.Next(0, {h})");
                sb.AppendLine($"{pad}Move-HumanMouse $destX $destY {screenW} {screenH} @{{ " + CfgHash(n.Props, mouseSpeedMin, mouseSpeedMax) + " }");
                break;
            }

            case "mouseMove":
            {
                // v0.9.0 — humanized via the same engine (Gentle preset) when the step's
                // "human" box is checked; raw instant MMOVE otherwise.
                if (PropEx.GetString(n.Props, "moveMode", "fixed") == "handSample"
                    && HandMovementSample.TryDecode(PropEx.GetString(n.Props, "handSample"), out var sample))
                {
                    foreach (var seg in HandMovementSample.Compact(sample.Segments, 48))
                    {
                        if (seg.Dx != 0 || seg.Dy != 0) sb.AppendLine($"{pad}Send-Cmd \"MMOVE|{seg.Dx},{seg.Dy},rel,2\"");
                        sb.AppendLine($"{pad}Step-Delay {seg.DelayMs}");
                    }
                }
                else if (PropEx.GetBool(n.Props, "human", true))
                    sb.AppendLine($"{pad}Move-HumanMouse {PropEx.GetInt(n.Props, "x", 600)} {PropEx.GetInt(n.Props, "y", 497)} {screenW} {screenH} @{{ {GentleHashFromProps(n.Props, mouseSpeedMin, mouseSpeedMax)} }}");
                else
                    sb.AppendLine($"{pad}Send-Cmd \"MMOVE|{PropEx.GetInt(n.Props, "x", 600)},{PropEx.GetInt(n.Props, "y", 497)},abs,0\"");
                break;
            }

            default:
            {
                bool secret = n.Type == "typeText" && PropEx.GetBool(n.Props, "secret");
                if (secret)
                    sb.AppendLine(pad + "# NOTE: sensitive text below — visible in plain text in this file; delete the file after use (§17.6)");
                foreach (var cmd in StepDefinitions.GetCommands(n))
                {
                    if (cmd.StartsWith("CLIPBOARD:"))
                    {
                        var text = cmd["CLIPBOARD:".Length..];
                        sb.AppendLine($"{pad}Set-Clipboard -Value '{text.Replace("'", "''")}'");
                        sb.AppendLine($"{pad}Send-Cmd 'KCOMBO|162+86'   # Ctrl+V");
                    }
                    else if (cmd == "KCOMBO|162+86")
                    {
                        // already emitted above for CLIPBOARD mode — skip duplicate
                    }
                    else if (cmd.StartsWith("DLY|"))
                    {
                        // v0.9.11 — DLY is an APP-side humanize pause (word/punctuation/thinking/
                        // typo). The old output sent it to the board as an unknown op; it must be
                        // a local Start-Sleep in the generated script.
                        sb.AppendLine($"{pad}Step-Delay {cmd["DLY|".Length..]}   # humanize pause");
                    }
                    else
                    {
                        sb.AppendLine($"{pad}Send-Cmd \"{Protect(cmd)}\"");
                    }
                }
                break;
            }
        }

        if (n.DelayMax > n.Delay)
            sb.AppendLine($"{pad}Step-Delay (Get-Random -Minimum {n.Delay} -Maximum {n.DelayMax + 1})   # random delay range (v0.7.8)");
        else if (n.Delay > 0)
            sb.AppendLine($"{pad}Step-Delay {n.Delay}");
    }

    private static string Protect(string s) => s.Replace("`", "``").Replace("\"", "`\"").Replace("$", "`$");

    /// <summary>v0.9.0 — per-step humanization hashtable literal for the generated script's
    /// Move-HumanMouse; values come from the Random Mouse Position dialog fields (old files
    /// fall back to the human defaults — same keys as HumanMouse.Config.FromProps).</summary>
    private static string CfgHash(System.Collections.Generic.IReadOnlyDictionary<string, object?> p, int speedMin, int speedMax)
    {
        int G(string k, int d) => PropEx.GetInt(p, k, d);
        int legacy = Math.Clamp(G("curvePct", 30), 0, 200);
        int curveMin = p.ContainsKey("curveMinPct") ? Math.Clamp(G("curveMinPct", 15), 0, 200) : Math.Max(0, legacy - 15);
        int curveMax = p.ContainsKey("curveMaxPct") ? Math.Clamp(G("curveMaxPct", 45), 0, 200) : Math.Min(200, legacy + 15);
        if (curveMax < curveMin) (curveMin, curveMax) = (curveMax, curveMin);
        int mtMin = Math.Max(0, G("moveTimeMin", 0));
        int mtMax = Math.Max(0, G("moveTimeMax", 0));
        if (mtMax < mtMin) (mtMin, mtMax) = (mtMax, mtMin);
        return $"pbMin={G("pauseBeforeMin", 120)}; pbMax={G("pauseBeforeMax", 450)}; paMin={G("pauseAfterMin", 150)}; paMax={G("pauseAfterMax", 600)}; " +
               $"midPct={Math.Clamp(G("midPauseChance", 12), 0, 100)}; midMin={G("midPauseMin", 100)}; midMax={G("midPauseMax", 400)}; " +
               $"idleMin={G("idleEveryMin", 5)}; idleMax={G("idleEveryMax", 12)}; idlePMin={G("idlePauseMin", 1000)}; idlePMax={G("idlePauseMax", 5000)}; " +
               $"ovPct={Math.Clamp(G("overshootChance", 15), 0, 100)}; curvMin={curveMin}; curvMax={curveMax}; mtMin={mtMin}; mtMax={mtMax}; spMin={Math.Max(0, speedMin)}; spMax={Math.Max(0, speedMax)}";
    }

    /// <summary>v0.9.0 — the Gentle preset (Mouse Position steps): single source of truth is
    /// HumanMouse.Config.Gentle, so app-run and generated-script behavior stay identical.</summary>
    private static string GentleHash(int speedMin, int speedMax)
    {
        var g = HumanMouse.Config.Gentle(speedMin, speedMax);
        return $"pbMin={g.PauseBeforeMinMs}; pbMax={g.PauseBeforeMaxMs}; paMin={g.PauseAfterMinMs}; paMax={g.PauseAfterMaxMs}; " +
               $"midPct={g.MidPauseChancePct}; midMin={g.MidPauseMinMs}; midMax={g.MidPauseMaxMs}; " +
               $"idleMin=0; idleMax=0; idlePMin=0; idlePMax=0; ovPct={g.OvershootChancePct}; curvMin={g.CurveMinPct}; curvMax={g.CurveMaxPct}; mtMin=0; mtMax=0; spMin={Math.Max(0, speedMin)}; spMax={Math.Max(0, speedMax)}";
    }

    /// <summary>v0.9.14 — Mouse Position carries Gentle-defaulted human fields now; they must
    /// reach the generated script instead of the fixed preset (mirrors FromProps gentleDefaults).</summary>
    private static string GentleHashFromProps(System.Collections.Generic.IReadOnlyDictionary<string, object?> p, int speedMin, int speedMax)
    {
        var g = HumanMouse.Config.FromProps(p, speedMin, speedMax, gentleDefaults: true);
        return $"pbMin={g.PauseBeforeMinMs}; pbMax={g.PauseBeforeMaxMs}; paMin={g.PauseAfterMinMs}; paMax={g.PauseAfterMaxMs}; " +
               $"midPct={g.MidPauseChancePct}; midMin={g.MidPauseMinMs}; midMax={g.MidPauseMaxMs}; " +
               $"idleMin=0; idleMax=0; idlePMin=0; idlePMax=0; ovPct={g.OvershootChancePct}; curvMin={g.CurveMinPct}; curvMax={g.CurveMaxPct}; mtMin={g.MoveTimeMinMs}; mtMax={g.MoveTimeMaxMs}; spMin={Math.Max(0, speedMin)}; spMax={Math.Max(0, speedMax)}";
    }

    private static long UnitMs(string unit) => unit switch
    {
        "second" => 1_000L,
        "minute" => 60_000L,
        "hour" => 3_600_000L,
        _ => 1L,
    };

    private static string EmitHeader()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# ═══════════════════════════════════ embedded bridge client (protocol v1, matches bridge/bridge.py) ═══════════════════════════════════");
        sb.AppendLine("Add-Type -AssemblyName System.Windows.Forms");
        sb.AppendLine("$script:br = $null");
        sb.AppendLine();
        sb.AppendLine("function __Send-Raw($obj) {");
        sb.AppendLine("    $script:br.StandardInput.WriteLine(($obj | ConvertTo-Json -Compress))");
        sb.AppendLine("    $script:br.StandardInput.Flush()");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function __Read-Event {");
        sb.AppendLine("    while ($true) {");
        sb.AppendLine("        $line = $script:br.StandardOutput.ReadLine()");
        sb.AppendLine("        if ($null -eq $line) { throw 'bridge closed' }");
        sb.AppendLine("        try { return ($line | ConvertFrom-Json) } catch { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function Send-Cmd([string]$cmd, [double]$TimeoutSec = 5) {");
        sb.AppendLine("    # TimeoutSec must exceed the command's own window for WSND/TRGSND/SCAL (design doc §15.4 rule 4)");
        sb.AppendLine("    __Send-Raw (@{ op = 'send'; cmd = $cmd; timeout = $TimeoutSec })");
        sb.AppendLine("    $reply = __Read-Event");
        sb.AppendLine("    if ($reply.event -eq 'reply') { return [string]$reply.reply }");
        sb.AppendLine("    if ($reply.event -eq 'error') { throw ('bridge: ' + $reply.message) }");
        sb.AppendLine("    throw ('unexpected event: ' + $reply.event)");
        sb.AppendLine("}");
        sb.AppendLine("function Send-Path([string]$pts, [string]$dlys) {");
        sb.AppendLine("    # v0.9.2 — streams a whole dense mouse path in ONE bridge op (bridge.py v0.9.2+)");
        sb.AppendLine("    __Send-Raw (@{ op = 'send_path'; pts = $pts; dlys = $dlys })");
        sb.AppendLine("    $reply = __Read-Event");
        sb.AppendLine("    if ($reply.event -eq 'reply') { return [string]$reply.reply }");
        sb.AppendLine("    if ($reply.event -eq 'error') { throw ('bridge: ' + $reply.message) }");
        sb.AppendLine("    if ($reply.event -eq 'aborted') { throw 'aborted' }");
        sb.AppendLine("    throw ('unexpected event: ' + $reply.event)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("function Step-Delay([int]$ms) { if ($ms -gt 0) { Start-Sleep -Milliseconds $ms } }");
        sb.AppendLine();
        // v0.9.0 — embedded human-mouse engine (WindMouse path + pause manager), mirroring
        // Services/HumanMouse.cs. PS 5.1-safe: New-Object System.Random — NOT [Math]::Random::Default
        // (that type/member does not exist and crashed the old generated scripts at runtime).
        sb.AppendLine("$script:rng = New-Object System.Random");
        sb.AppendLine("$script:mouseMovesSinceIdle = 0");
        sb.AppendLine("$script:mouseNextIdleAt = -1");
        sb.AppendLine("function __R([int]$a, [int]$b) { if ($b -lt $a) { $t = $a; $a = $b; $b = $t }; if ($b -le 0) { return 0 }; if ($a -eq $b) { return [int]$a }; return [int]$script:rng.Next($a, $b + 1) }");
                sb.AppendLine("function Move-HumanMouse([int]$tx, [int]$ty, [int]$sw, [int]$sh, [hashtable]$c) {");
        sb.AppendLine("    $pos = [System.Windows.Forms.Cursor]::Position   # real cursor — the old block curved from the region corner");
        sb.AppendLine("    $cx = [double]$pos.X; $cy = [double]$pos.Y");
        sb.AppendLine("    if ($tx -lt 0) { $tx = 0 }; if ($tx -ge $sw) { $tx = $sw - 1 }");
        sb.AppendLine("    if ($ty -lt 0) { $ty = 0 }; if ($ty -ge $sh) { $ty = $sh - 1 }");
        sb.AppendLine("    $pre = __R ([int]$c.pbMin) ([int]$c.pbMax); if ($pre -gt 0) { Start-Sleep -Milliseconds $pre }   # reaction pause");
        sb.AppendLine("    $dx = $tx - $cx; $dy = $ty - $cy");
        sb.AppendLine("    $dist = [Math]::Sqrt($dx*$dx + $dy*$dy)");
        sb.AppendLine("    # v0.9.8 — range policy: continuous quantities get fresh smooth profiles THROUGHOUT each move");
        sb.AppendLine("    $speedEnabled = [int]$c.spMax -gt 0; $spA = [int]$c.spMin; $spB = [int]$c.spMax");
        sb.AppendLine("    if ($spB -lt $spA) { $tmp = $spA; $spA = $spB; $spB = $tmp }");
        sb.AppendLine("    $spLo = [Math]::Max(150, $spA); $spHi = [Math]::Max($spLo, $spB)");
        sb.AppendLine("    $totalMs = if ($speedEnabled) { [int][Math]::Min(30000, [Math]::Max(60, $dist * 1000.0 / [Math]::Max(1.0, ($spLo + $spHi) / 2.0))) } else { 0 }");
        sb.AppendLine("    $mtMin=[int]$c.mtMin; $mtMax=[int]$c.mtMax; if ($mtMax -lt $mtMin) { $tmp=$mtMin; $mtMin=$mtMax; $mtMax=$tmp }");
        sb.AppendLine("    $targetMoveMs = if ($mtMax -gt 0) { __R ([Math]::Max(1,$mtMin)) ([Math]::Max(1,$mtMax)) } else { 0 }   # v0.9.10 fresh duration target per move");
        sb.AppendLine("    $curveMinPct = [Math]::Min(200, [Math]::Max(0, [int]$c.curvMin)); $curveMaxPct = [Math]::Min(200, [Math]::Max(0, [int]$c.curvMax))");
        sb.AppendLine("    if ($curveMaxPct -lt $curveMinPct) { $tmp = $curveMinPct; $curveMinPct = $curveMaxPct; $curveMaxPct = $tmp }");
        sb.AppendLine("    $curve = (__R $curveMinPct $curveMaxPct) / 100.0; $curveScale = [Math]::Min(1.0, $curve)");
        sb.AppendLine("    $curveKnotCount = [Math]::Max(4, [Math]::Min(8, 4 + [int]($dist / 320.0)))");
        sb.AppendLine("    $curveKnots = @(); $upperCurve = $script:rng.Next(2) -eq 1");
        sb.AppendLine("    for ($k = 0; $k -lt $curveKnotCount; $k++) {");
        sb.AppendLine("        if ($curveMinPct -eq $curveMaxPct) { $curveKnots += [double]$curveMinPct }");
        sb.AppendLine("        else { $band = if ($upperCurve) { 0.60 + $script:rng.NextDouble() * 0.40 } else { $script:rng.NextDouble() * 0.40 }; $curveKnots += $curveMinPct + ($curveMaxPct-$curveMinPct)*$band; $upperCurve = -not $upperCurve }");
        sb.AppendLine("    }");
        sb.AppendLine("    $arcMode = $curveMaxPct -gt 100 -and $dist -ge 80");
        sb.AppendLine("    $arcSide = 0; $arcHeight = 0.0; $arcFit = 1.0; $arcSkew = $script:rng.NextDouble() * 0.14 - 0.07");
        sb.AppendLine("    $arcWobble = 0.025 + $script:rng.NextDouble() * 0.045; $arcPhase = $script:rng.NextDouble() * 2.0 * [Math]::PI");
        sb.AppendLine("    if ($arcMode) {");
        sb.AppendLine("        $ux0 = $dx / $dist; $uy0 = $dy / $dist; $nx0 = -$uy0; $ny0 = $ux0");
        sb.AppendLine("        $heightRatio = if ($curveMaxPct -le 100) { 0.08 * [Math]::Pow($curveMaxPct/100.0, 1.15) } else { 0.08 + 0.42 * [Math]::Sqrt(($curveMaxPct-100)/100.0) }");
        sb.AppendLine("        $desiredHeight = $dist * $heightRatio");
        sb.AppendLine("        $midX = ($cx + $tx) / 2.0; $midY = ($cy + $ty) / 2.0");
        sb.AppendLine("        $roomPos = [double]::PositiveInfinity; $roomNeg = [double]::PositiveInfinity");
        sb.AppendLine("        if ([Math]::Abs($nx0) -gt 0.000001) {");
        sb.AppendLine("            $r = if ($nx0 -gt 0) { ($sw - 3 - $midX) / $nx0 } else { (2 - $midX) / $nx0 }; $roomPos = [Math]::Min($roomPos, $r)");
        sb.AppendLine("            $nnx = -$nx0; $r = if ($nnx -gt 0) { ($sw - 3 - $midX) / $nnx } else { (2 - $midX) / $nnx }; $roomNeg = [Math]::Min($roomNeg, $r)");
        sb.AppendLine("        }");
        sb.AppendLine("        if ([Math]::Abs($ny0) -gt 0.000001) {");
        sb.AppendLine("            $r = if ($ny0 -gt 0) { ($sh - 3 - $midY) / $ny0 } else { (2 - $midY) / $ny0 }; $roomPos = [Math]::Min($roomPos, $r)");
        sb.AppendLine("            $nny = -$ny0; $r = if ($nny -gt 0) { ($sh - 3 - $midY) / $nny } else { (2 - $midY) / $nny }; $roomNeg = [Math]::Min($roomNeg, $r)");
        sb.AppendLine("        }");
        sb.AppendLine("        $fitPos = [Math]::Min(1.0, [Math]::Max(0.0, 0.92 * $roomPos / $desiredHeight))");
        sb.AppendLine("        $fitNeg = [Math]::Min(1.0, [Math]::Max(0.0, 0.92 * $roomNeg / $desiredHeight))");
        sb.AppendLine("        if ($fitPos -ge 0.90 -and $fitNeg -ge 0.90) { $arcSide = if ($script:rng.Next(2) -eq 0) { -1 } else { 1 } }");
        sb.AppendLine("        elseif ($fitPos -ge $fitNeg) { $arcSide = 1 } else { $arcSide = -1 }");
        sb.AppendLine("        $arcFit = if ($arcSide -gt 0) { $fitPos } else { $fitNeg }; $arcHeight = $desiredHeight * $arcFit");
        sb.AppendLine("    }");
        sb.AppendLine("    $legs = @()   # optional overshoot leg (aim past the target) + correction leg");
        sb.AppendLine("    if ($arcMode) { $legs += ,@($tx, $ty, $totalMs, $false) }");
        sb.AppendLine("    elseif ($dist -ge 60 -and [int]$c.ovPct -gt 0 -and $script:rng.Next(100) -lt [int]$c.ovPct) {");
        sb.AppendLine("        $over = [int][Math]::Min(20, [Math]::Max(2, $dist * (0.03 + $script:rng.NextDouble() * 0.05) * $curveScale))   # v0.9.5: overshoot scales with arc");
        sb.AppendLine("        $perp = [int]($script:rng.NextDouble() * (2.0 + $curveScale * 5.0) - (1.0 + $curveScale * 2.5))   # v0.9.5: lateral error scales with arc");
        sb.AppendLine("        $ux = $dx / $dist; $uy = $dy / $dist");
        sb.AppendLine("        $ox = [int]($tx + $ux * $over - $uy * $perp); $oy = [int]($ty + $uy * $over + $ux * $perp)");
        sb.AppendLine("        if ($ox -lt 0) { $ox = 0 }; if ($ox -ge $sw) { $ox = $sw - 1 }");
        sb.AppendLine("        if ($oy -lt 0) { $oy = 0 }; if ($oy -ge $sh) { $oy = $sh - 1 }");
        sb.AppendLine("        $legs += ,@($ox, $oy, [int]($totalMs * 0.8), $true)");
        sb.AppendLine("        $legs += ,@($tx, $ty, [int]($totalMs * 0.25) + 60, $false)");
        sb.AppendLine("    } else { $legs += ,@($tx, $ty, $totalMs, $false) }");
        sb.AppendLine("    for ($li = 0; $li -lt $legs.Count; $li++) {");
        sb.AppendLine("        $ex = [int]$legs[$li][0]; $ey = [int]$legs[$li][1]; $budget = [int]$legs[$li][2]");
        sb.AppendLine("        $d0 = [Math]::Sqrt(($ex-$cx)*($ex-$cx) + ($ey-$cy)*($ey-$cy))");
        sb.AppendLine("        if ($d0 -lt 3) { Send-Cmd \"MMOVE|$ex,$ey,abs,0\"; $cx = $ex; $cy = $ey; continue }");
        sb.AppendLine("        $px = @(); $py = @()");
        sb.AppendLine("        if ($arcMode -and $li -eq 0) {");
        sb.AppendLine("            # One continuous irregular half-ellipse; includes the real start so resampling cannot jump.");
        sb.AppendLine("            $samples = [Math]::Max(32, [Math]::Min(240, [int][Math]::Ceiling($d0 / 12.0)))");
        sb.AppendLine("            $uxA = ($ex - $cx) / $d0; $uyA = ($ey - $cy) / $d0; $nxA = -$uyA; $nyA = $uxA");
        sb.AppendLine("            for ($ai = 0; $ai -le $samples; $ai++) {");
        sb.AppendLine("                $at = $ai / [double]$samples");
        sb.AppendLine("                $aq = [Math]::Min(1.0, [Math]::Max(0.0, $at + $arcSkew * [Math]::Sin([Math]::PI * $at)))");
        sb.AppendLine("                $along = 0.5 - 0.5 * [Math]::Cos([Math]::PI * $aq)");
        sb.AppendLine("                $shape = [Math]::Sin([Math]::PI * $aq) * (1.0 + $arcWobble * [Math]::Sin(2.0 * [Math]::PI * $at + $arcPhase))");
        sb.AppendLine("                $kp = $at * ($curveKnots.Count-1); $ki = [Math]::Min($curveKnots.Count-2, [int][Math]::Floor($kp)); $ku = $kp-$ki; $ks = $ku*$ku*(3.0-2.0*$ku)");
        sb.AppendLine("                $liveCurvePct = $curveKnots[$ki] + ($curveKnots[$ki+1]-$curveKnots[$ki])*$ks");
        sb.AppendLine("                $liveRatio = if ($liveCurvePct -le 100) { 0.08*[Math]::Pow($liveCurvePct/100.0,1.15) } else { 0.08+0.42*[Math]::Sqrt(($liveCurvePct-100)/100.0) }");
        sb.AppendLine("                $normal = $arcSide * $d0 * $liveRatio * $arcFit * [Math]::Max(0.0, $shape)");
        sb.AppendLine("                $px += [int][Math]::Round($cx + $uxA * $d0 * $along + $nxA * $normal)");
        sb.AppendLine("                $py += [int][Math]::Round($cy + $uyA * $d0 * $along + $nyA * $normal)");
        sb.AppendLine("            }");
        sb.AppendLine("            $px[$px.Count-1] = $ex; $py[$py.Count-1] = $ey");
        sb.AppendLine("            $arcLen = 0.0; for ($ai = 1; $ai -lt $px.Count; $ai++) { $arcLen += [Math]::Sqrt(($px[$ai]-$px[$ai-1])*($px[$ai]-$px[$ai-1]) + ($py[$ai]-$py[$ai-1])*($py[$ai]-$py[$ai-1])) }");
        sb.AppendLine("            if ($budget -gt 0) { $budget = [int][Math]::Min(30000, [Math]::Max(60, $budget * [Math]::Max(1.0, $arcLen / $d0))) }");
        sb.AppendLine("        } else {");
        sb.AppendLine("            $wx = 0.0; $wy = 0.0; $vx = 0.0; $vy = 0.0; $x = $cx; $y = $cy; $guard = 0");
        sb.AppendLine("            $maxStep = [Math]::Min(30.0, [Math]::Max(6.0, $d0 / 15.0))");
        sb.AppendLine("            $stopR = [Math]::Min(8.0, [Math]::Max(2.0, $d0 * 0.02))");
        sb.AppendLine("            $px += [int][Math]::Round($cx); $py += [int][Math]::Round($cy)");
        sb.AppendLine("            while ($guard -lt 2000) {");
        sb.AppendLine("                $guard++");
        sb.AppendLine("                $d = [Math]::Sqrt(($ex-$x)*($ex-$x) + ($ey-$y)*($ey-$y))");
        sb.AppendLine("                if ($d -lt $stopR) { break }");
        sb.AppendLine("                $cp = [Math]::Min(1.0,[Math]::Max(0.0,1.0-$d/$d0)); $kp=$cp*($curveKnots.Count-1); $ki=[Math]::Min($curveKnots.Count-2,[int][Math]::Floor($kp)); $ku=$kp-$ki; $ks=$ku*$ku*(3.0-2.0*$ku)");
        sb.AppendLine("                $liveCurvePct=$curveKnots[$ki]+($curveKnots[$ki+1]-$curveKnots[$ki])*$ks; $normalCurve=[Math]::Min(1.0,$liveCurvePct/100.0)");
        sb.AppendLine("                $wind=(0.3+$normalCurve*3.0)*[Math]::Min(1.0,[Math]::Max(0.35,$d0/400.0))");
        sb.AppendLine("                $wMag = [Math]::Min($wind, $d)");
        sb.AppendLine("                if ($d -ge $stopR * 4) {");
        sb.AppendLine("                    $wx = $wx / 1.7320508 + (2 * $script:rng.NextDouble() - 1) * $wMag / 2.2360679");
        sb.AppendLine("                    $wy = $wy / 1.7320508 + (2 * $script:rng.NextDouble() - 1) * $wMag / 2.2360679");
        sb.AppendLine("                } else {");
        sb.AppendLine("                    $wx = $wx / 1.7320508; $wy = $wy / 1.7320508");
        sb.AppendLine("                    $maxStep = [Math]::Max(2.5, $maxStep / 2.2360679)");
        sb.AppendLine("                }");
        sb.AppendLine("                $vx += $wx + 14.0 * ($ex - $x) / $d; $vy += $wy + 14.0 * ($ey - $y) / $d");
        sb.AppendLine("                $vm = [Math]::Sqrt($vx*$vx + $vy*$vy)");
        sb.AppendLine("                if ($vm -gt $maxStep) { $vx = $vx / $vm * $maxStep; $vy = $vy / $vm * $maxStep }");
        sb.AppendLine("                $x += $vx; $y += $vy");
        sb.AppendLine("                $px += [int][Math]::Round($x); $py += [int][Math]::Round($y)");
        sb.AppendLine("            }");
        sb.AppendLine("            $px += $ex; $py += $ey");
        sb.AppendLine("        }");
        sb.AppendLine("        # v0.9.8 — micro-step spacing also changes smoothly throughout 2.0..3.2px");
        sb.AppendLine("        $sourceLen=0.0; for ($i=1; $i -lt $px.Count; $i++) { $sourceLen += [Math]::Sqrt(($px[$i]-$px[$i-1])*($px[$i]-$px[$i-1])+($py[$i]-$py[$i-1])*($py[$i]-$py[$i-1])) }");
        sb.AppendLine("        $spacingKnots=@(); $upperSpacing=$script:rng.Next(2) -eq 1; for ($k=0; $k -lt 5; $k++) { $band=if ($upperSpacing) {0.60+$script:rng.NextDouble()*0.40} else {$script:rng.NextDouble()*0.40}; $spacingKnots += 2.0+1.2*$band; $upperSpacing=-not $upperSpacing }");
        sb.AppendLine("        $rx = @(); $ry = @(); $nextAt = [double]$spacingKnots[0]; $acc = 0.0");
        sb.AppendLine("        for ($i = 1; $i -lt $px.Count; $i++) {");
        sb.AppendLine("            $x0 = [double]$px[$i-1]; $y0 = [double]$py[$i-1]");
        sb.AppendLine("            $seg = [Math]::Sqrt(($px[$i]-$x0)*($px[$i]-$x0) + ($py[$i]-$y0)*($py[$i]-$y0))");
        sb.AppendLine("            if ($seg -lt 0.001) { continue }");
        sb.AppendLine("            while ($acc + $seg -ge $nextAt) {");
        sb.AppendLine("                $t = ($nextAt - $acc) / $seg");
        sb.AppendLine("                $rx += [int][Math]::Round($x0 + ($px[$i]-$x0)*$t)");
        sb.AppendLine("                $ry += [int][Math]::Round($y0 + ($py[$i]-$y0)*$t)");
        sb.AppendLine("                $phase=if ($sourceLen -gt 0) {[Math]::Min(1.0,$nextAt/$sourceLen)} else {1.0}; $kp=$phase*($spacingKnots.Count-1); $ki=[Math]::Min($spacingKnots.Count-2,[int][Math]::Floor($kp)); $ku=$kp-$ki; $ks=$ku*$ku*(3.0-2.0*$ku)");
        sb.AppendLine("                $liveSpacing=$spacingKnots[$ki]+($spacingKnots[$ki+1]-$spacingKnots[$ki])*$ks; $nextAt += [Math]::Max(0.5,$liveSpacing)");
        sb.AppendLine("            }");
        sb.AppendLine("            $acc += $seg");
        sb.AppendLine("        }");
        sb.AppendLine("        if ($rx.Count -eq 0 -or $rx[$rx.Count-1] -ne $ex -or $ry[$ry.Count-1] -ne $ey) { $rx += $ex; $ry += $ey }");
        sb.AppendLine("        $n = $rx.Count");
        sb.AppendLine("        # v0.9.8 — actual speed glides through the configured MIN/MAX during this same leg");
        sb.AppendLine("        $segLens=@(); $moveLen=0.0; $lx=[double]$cx; $ly=[double]$cy; for ($i=0; $i -lt $n; $i++) { $sl=[Math]::Sqrt(($rx[$i]-$lx)*($rx[$i]-$lx)+($ry[$i]-$ly)*($ry[$i]-$ly)); $segLens += $sl; $moveLen += $sl; $lx=$rx[$i]; $ly=$ry[$i] }");
        sb.AppendLine("        $speedKnotCount=[Math]::Max(4,[Math]::Min(9,4+[int]($n/120))); $speedKnots=@(); $upperSpeed=$script:rng.Next(2)-eq 1");
        sb.AppendLine("        for ($k=0; $k -lt $speedKnotCount; $k++) { if ($spLo -eq $spHi) {$speedKnots += [double]$spLo} else {$forceLow=($k -eq 0 -or $k -eq $speedKnotCount-1); $band=if ($forceLow) {$script:rng.NextDouble()*0.18} elseif ($upperSpeed) {0.60+$script:rng.NextDouble()*0.40} else {$script:rng.NextDouble()*0.40}; $speedKnots += $spLo+($spHi-$spLo)*$band; $upperSpeed=-not $upperSpeed} }");
        sb.AppendLine("        $wts=@(); $wSum=0.0; $travelled=0.0; for ($i=0; $i -lt $n; $i++) { if (($speedEnabled -or $targetMoveMs -gt 0) -and $moveLen -gt 0) {$phase=[Math]::Min(1.0,($travelled+$segLens[$i]*0.5)/$moveLen); $kp=$phase*($speedKnots.Count-1); $ki=[Math]::Min($speedKnots.Count-2,[int][Math]::Floor($kp)); $ku=$kp-$ki; $ks=$ku*$ku*(3.0-2.0*$ku); $liveSpeed=$speedKnots[$ki]+($speedKnots[$ki+1]-$speedKnots[$ki])*$ks; $wi=$segLens[$i]*1000.0/[Math]::Max(1.0,$liveSpeed); $wts += $wi; $wSum += $wi} else {$wts += 0.0}; $travelled += $segLens[$i] }");
        sb.AppendLine("        $ds=@(); for ($i=0; $i -lt $n; $i++) { if ($targetMoveMs -gt 0 -and $wSum -gt 0) {$ds += [Math]::Max(1,[int][Math]::Round($wts[$i]*$targetMoveMs/$wSum))} elseif ($speedEnabled) {$ds += [Math]::Max(1,[int][Math]::Round($wts[$i]))} else {$ds += 0} }   # duration target normalizes the same smooth speed shape");
        sb.AppendLine("        if ([int]$c.midPct -gt 0 -and $n -gt 8 -and $script:rng.Next(100) -lt [int]$c.midPct) { $mi = 2 + $script:rng.Next($n - 4); $ds[$mi] = $ds[$mi] + (__R ([int]$c.midMin) ([int]$c.midMax)) }   # hesitation");
        sb.AppendLine("        $pack = @()   # clamp on-screen + pack");
        sb.AppendLine("        for ($i = 0; $i -lt $n; $i++) {");
        sb.AppendLine("            $mx = $rx[$i]; if ($mx -lt 0) { $mx = 0 }; if ($mx -ge $sw) { $mx = $sw - 1 }");
        sb.AppendLine("            $my = $ry[$i]; if ($my -lt 0) { $my = 0 }; if ($my -ge $sh) { $my = $sh - 1 }");
        sb.AppendLine("            $pack += \"$mx,$my\"");
        sb.AppendLine("        }");
        sb.AppendLine("        try {");
        sb.AppendLine("            Send-Path ($pack -join ';') ($ds -join ';')   # ONE bridge op — no per-point round-trip");
        sb.AppendLine("        } catch {");
        sb.AppendLine("            if ($_.Exception.Message -match 'unknown op') {   # old bridge.py: firmware-smoothstep fallback");
        sb.AppendLine("                for ($i = 0; $i -lt $n; $i += 12) {");
        sb.AppendLine("                    $p2 = $pack[$i] -split ','");
        sb.AppendLine("                    Send-Cmd \"MMOVE|$($p2[0]),$($p2[1]),abs,1\"");
        sb.AppendLine("                    $dsum = 0; for ($j = $i; $j -lt [Math]::Min($i + 12, $n); $j++) { $dsum += $ds[$j] }");
        sb.AppendLine("                    if ($dsum -gt 0) { Start-Sleep -Milliseconds $dsum }");
        sb.AppendLine("                }");
        sb.AppendLine("                Send-Cmd \"MMOVE|$ex,$ey,abs,1\"");
        sb.AppendLine("            } else { throw }");
        sb.AppendLine("        }");
        sb.AppendLine("        if ($legs[$li][3] -eq $true) { Start-Sleep -Milliseconds (__R 60 180) }   # re-aim at the overshoot point");
        sb.AppendLine("        $cx = $ex; $cy = $ey");
        sb.AppendLine("    }");
        sb.AppendLine("    $post = __R ([int]$c.paMin) ([int]$c.paMax); if ($post -gt 0) { Start-Sleep -Milliseconds $post }   # settle pause");
        sb.AppendLine("    if ([int]$c.idlePMax -gt 0 -and [int]$c.idleMax -gt 0) {   # long every-N-moves break (0-5000 ms)");
        sb.AppendLine("        $script:mouseMovesSinceIdle++");
        sb.AppendLine("        if ($script:mouseNextIdleAt -lt 0) { $script:mouseNextIdleAt = [Math]::Max(1, (__R ([int]$c.idleMin) ([int]$c.idleMax))) }");
        sb.AppendLine("        if ($script:mouseMovesSinceIdle -ge $script:mouseNextIdleAt) {");
        sb.AppendLine("            $script:mouseMovesSinceIdle = 0");
        sb.AppendLine("            $script:mouseNextIdleAt = [Math]::Max(1, (__R ([int]$c.idleMin) ([int]$c.idleMax)))");
        sb.AppendLine("            Start-Sleep -Milliseconds (__R ([int]$c.idlePMin) ([int]$c.idlePMax))");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("function Start-Board {");
        sb.AppendLine("    $bridgePy = Join-Path $PSScriptRoot 'bridge\\bridge.py'");
        sb.AppendLine("    if (-not (Test-Path $bridgePy)) { $bridgePy = Join-Path $PSScriptRoot 'bridge.py' }");
        var q = (char)34; var bt = (char)96;
        sb.AppendLine($"    $psi = [Diagnostics.ProcessStartInfo]::new('python', {bt}{q}$bridgePy{q}{bt} --pydir {bt}{q}$PythonDir{q}{bt}{q})");
        sb.AppendLine("    $psi.RedirectStandardInput = $true; $psi.RedirectStandardOutput = $true");
        sb.AppendLine("    $psi.RedirectStandardError = $true; $psi.UseShellExecute = $false; $psi.CreateNoWindow = $true");
        sb.AppendLine("    $script:br = [Diagnostics.Process]::Start($psi)");
        sb.AppendLine("    __Send-Raw (@{ op = 'connect'; port = $Port })");
        sb.AppendLine("    $ev = __Read-Event");
        sb.AppendLine("    if ($ev.event -ne 'connected') { throw ('connect failed: ' + $ev.message) }");
        sb.AppendLine("    Write-Host ('connected to board on ' + $ev.port + ' (FW ' + $ev.fw + ', encrypted)')");
        sb.AppendLine("}");
        return sb.ToString();
    }

}
