using System.IO.Ports; using System.IO; using Ams.UI.Services;
namespace ProMicroProvisioner.Services;
public static class ArduinoIspService {
 const byte Eop=0x20,InSync=0x14,Ok=0x10; const int Page=128,BootStart=0x7000;
 public static async Task<List<string>> DetectAsync(Action<string> log,CancellationToken ct){var hits=new List<string>();foreach(var port in SerialPort.GetPortNames().Order()){ct.ThrowIfCancellationRequested();log($"Probe {port}…");if(await Task.Run(()=>Probe(port),ct)){hits.Add(port);log($"ArduinoISP: {port}");}}return hits;}
 static bool Probe(string port){try{using var s=Open(port,700);s.DiscardInBuffer();s.Write(new byte[]{0x30,Eop},0,2);return s.ReadByte()==InSync&&s.ReadByte()==Ok;}catch{return false;}}
 static SerialPort Open(string port,int timeout=2000){var s=new SerialPort(port,19200){DtrEnable=true,RtsEnable=true,ReadTimeout=timeout,WriteTimeout=timeout};s.Open();Thread.Sleep(700);s.DiscardInBuffer();return s;}
 sealed class Stk:IDisposable{readonly SerialPort s;public Stk(string p){s=Open(p);}public void Dispose()=>s.Dispose();byte[] Cmd(byte[] payload,int n=0){s.DiscardInBuffer();s.Write(payload.Concat(new[]{Eop}).ToArray(),0,payload.Length+1);if(s.ReadByte()!=InSync)throw new IOException("STK500 not in sync");var r=new byte[n];for(int i=0;i<n;i++)r[i]=(byte)s.ReadByte();if(s.ReadByte()!=Ok)throw new IOException("STK500 command failed");return r;}public void Sync()=>Cmd(new byte[]{0x30});public void SetDevice()=>Cmd(new byte[]{0x42,0x44,0,0,1,1,1,1,3,0xff,0xff,0xff,0xff,0,0x80,4,0,0,0,0x80,0});public void Enter()=>Cmd(new byte[]{0x50});public void Leave()=>Cmd(new byte[]{0x51});public byte[] Signature()=>Cmd(new byte[]{0x75},3);public byte Uni(byte a,byte b,byte c,byte d)=>Cmd(new byte[]{0x56,a,b,c,d},1)[0];public void Erase(){Uni(0xac,0x80,0,0);Thread.Sleep(500);}void Addr(int a)=>Cmd(new byte[]{0x55,(byte)(a>>1),(byte)(a>>9)});public void Write(int a,byte[] d){Addr(a);Cmd(new[]{(byte)0x64,(byte)(d.Length>>8),(byte)d.Length,(byte)'F'}.Concat(d).ToArray());}public byte[] Read(int a,int n){Addr(a);return Cmd(new byte[]{0x74,(byte)(n>>8),(byte)n,(byte)'F'},n);}public void Fuse(byte op,byte value){Uni(0xac,op,0,value);Thread.Sleep(60);}public void Lock(){Uni(0xac,0xe0,0,0x2f);Thread.Sleep(60);}}
 public static async Task InstallAsync(string port,string bootHex,string appHex,string backupDir,Action<string> log,IProgress<int>? progress,CancellationToken ct)=>await Task.Run(()=>{Directory.CreateDirectory(backupDir);using var stk=new Stk(port);stk.Sync();stk.SetDevice();stk.Enter();var sig=stk.Signature();if(!sig.SequenceEqual(new byte[]{0x1e,0x95,0x87}))throw new InvalidDataException($"Target signature {Convert.ToHexString(sig)} is not ATmega32U4");log("ATmega32U4 confirmed");var old=new byte[0x8000];for(int a=0;a<old.Length;a+=256){ct.ThrowIfCancellationRequested();Array.Copy(stk.Read(a,256),0,old,a,256);}File.WriteAllBytes(Path.Combine(backupDir,"flash-before.bin"),old);var app=BoardHexService.ParseHex(appHex);var boot=BoardHexService.ParseHex(bootHex);if(app.Skip(BootStart).Any(b=>b!=0xff))throw new InvalidDataException("Application HEX touches bootloader region");if(boot.Take(BootStart).Any(b=>b!=0xff))throw new InvalidDataException("Bootloader HEX touches application region");var image=new byte[0x8000];Array.Fill(image,(byte)0xff);Array.Copy(app,image,BootStart);Array.Copy(boot,BootStart,image,BootStart,0x1000);log("Chip erase (once)");stk.Erase();var pages=Enumerable.Range(0,image.Length/Page).Where(i=>image.Skip(i*Page).Take(Page).Any(b=>b!=0xff)).ToList();for(int j=0;j<pages.Count;j++){ct.ThrowIfCancellationRequested();int a=pages[j]*Page;stk.Write(a,image.Skip(a).Take(Page).ToArray());progress?.Report((j+1)*70/pages.Count);}log("Verifying application + bootloader");for(int j=0;j<pages.Count;j++){int a=pages[j]*Page;if(!stk.Read(a,Page).SequenceEqual(image.Skip(a).Take(Page)))throw new IOException($"Verify failed at 0x{a:X4}");progress?.Report(70+(j+1)*25/pages.Count);}stk.Fuse(0xa0,0xff);stk.Fuse(0xa8,0xd8);stk.Fuse(0xa4,0xcb);stk.Lock();stk.Leave();progress?.Report(100);log("Install and verify complete; fuses FF/D8/CB, lock 2F");},ct);
}
