/* Generated by tools/generate_abvm_abi.py. Do not edit. */
#ifndef AMS_ABVM_ABI1_H
#define AMS_ABVM_ABI1_H
#include <stdint.h>

#define ABVM_MAGIC 0x31504241u
#define ABVM_FORMAT_VERSION 2u
#define ABVM_VM_ABI 1u
#define ABVM_HEADER_SIZE 128u
#define ABVM_INSTRUCTION_SIZE 16u
#define ABVM_ROUTE_SIZE 16u
#define ABVM_RESOURCE_SIZE 36u
#define ABVM_LIMIT_FRAMES 8u
#define ABVM_LIMIT_LANES 2u
#define ABVM_LIMIT_ACTORS 4u
#define ABVM_LIMIT_EVENTS 4u
#define ABVM_LIMIT_INTERRUPTS 1u
#define ABVM_LIMIT_SOUND_PROFILES 8u
#define ABVM_LIMIT_SOUND_LISTENERS 1u
#define ABVM_LIMIT_PWM_CHANNELS 1u
#define ABVM_LIMIT_PACKAGE_ITEMS 32u

typedef enum AbvmOpcode {
    ABVM_OP_END = 0,
    ABVM_OP_DELAY = 1,
    ABVM_OP_KEY = 2,
    ABVM_OP_KDOWN = 3,
    ABVM_OP_KUP = 4,
    ABVM_OP_TYPE = 5,
    ABVM_OP_RMOUSE = 6,
    ABVM_OP_BEEP = 7,
    ABVM_OP_LOOP_ENTER = 10,
    ABVM_OP_LOOP_NEXT = 11,
    ABVM_OP_RPKG_ENTER = 12,
    ABVM_OP_ITEM_END = 13,
    ABVM_OP_SCOPE_BEGIN = 20,
    ABVM_OP_LANE_END = 21,
    ABVM_OP_WATCH = 22,
    ABVM_OP_JUMP = 30,
} AbvmOpcode;

typedef enum AbvmConstantKind {
    ABVM_CONST_UTF8 = 1,
    ABVM_CONST_TYPE = 2,
    ABVM_CONST_MOUSE = 3,
    ABVM_CONST_RANGES = 4,
    ABVM_CONST_SCOPE = 5,
    ABVM_CONST_SOUND = 6,
    ABVM_CONST_LIGHT = 7,
    ABVM_CONST_GUARD = 8,
    ABVM_CONST_CYCLE = 9,
} AbvmConstantKind;

typedef enum AbvmScopePolicy {
    ABVM_SCOPE_JOIN_ALL = 1,
    ABVM_SCOPE_CANCEL_ON_ANY = 2,
    ABVM_SCOPE_CANCEL_ON_TERMINAL_LANE = 3,
    ABVM_SCOPE_KEEP_RUNNING_UNTIL_CANCELLED = 4,
} AbvmScopePolicy;

typedef enum AbvmRoutePolicy {
    ABVM_ROUTE_DENY = 0,
    ABVM_ROUTE_ABORT_AND_START = 1,
    ABVM_ROUTE_INTERRUPT_AND_RESUME = 2,
    ABVM_ROUTE_CANCEL_SCOPE_AND_CONTINUE = 3,
    ABVM_ROUTE_ABORT_AND_RESTART = 4,
} AbvmRoutePolicy;

typedef enum AbvmRouteClockPolicy {
    ABVM_CLOCK_WALL = 0,
    ABVM_CLOCK_ACTIVE = 256,
} AbvmRouteClockPolicy;

typedef enum AbvmRouteFlag {
    ABVM_ROUTE_FLAG_PAUSE_RELEASE_HID = 512,
} AbvmRouteFlag;

#pragma pack(push, 1)
typedef struct AbvmHeader {
    uint32_t magic;
    uint16_t format_version;
    uint16_t vm_abi;
    uint32_t flags, file_size, header_size;
    uint32_t code_offset, code_count;
    uint32_t constant_offset, constant_size;
    uint32_t route_offset, route_count;
    uint32_t resource_offset, resource_size, crc32;
    uint16_t max_frames, max_lanes;
    uint8_t source_sha256[32], program_sha256[32];
    uint32_t reserved;
} AbvmHeader;

typedef struct AbvmInstruction {
    uint8_t opcode, flags;
    uint16_t operand_a;
    uint32_t operand_b, operand_c, operand_d;
} AbvmInstruction;

typedef struct AbvmRoute {
    uint16_t route_id, policy_flags;
    uint32_t pc, length, name_constant;
} AbvmRoute;

typedef struct AbvmResourceCertificate {
    uint16_t version, size, max_frames, max_lanes;
    uint16_t max_actors, max_events, max_interrupts;
    uint16_t sound_profiles, sound_listeners, pwm_channels;
    uint32_t max_constant_bytes, max_type_bytes, max_mouse_bytes;
    uint32_t capabilities;
} AbvmResourceCertificate;
#pragma pack(pop)

_Static_assert(sizeof(AbvmHeader) == ABVM_HEADER_SIZE, "ABVM header layout");
_Static_assert(sizeof(AbvmInstruction) == ABVM_INSTRUCTION_SIZE,
               "ABVM instruction layout");
_Static_assert(sizeof(AbvmRoute) == ABVM_ROUTE_SIZE, "ABVM route layout");
_Static_assert(sizeof(AbvmResourceCertificate) == ABVM_RESOURCE_SIZE,
               "ABVM resource layout");

#endif
