#!/usr/bin/env python3
"""Generate the fixed-capacity, patchable ABP flash slot for native Pico UF2."""
from __future__ import annotations
import argparse, hashlib
from pathlib import Path
SLOT_MAGIC=b"AMSABVMSLOT1\0\0\0\0"; SLOT_VERSION=1; SLOT_HEADER_SIZE=64; DEFAULT_CAPACITY=512*1024

def _rows(data:bytes,width:int=12)->str:
    return "\n".join("        "+", ".join(f"0x{v:02x}" for v in data[i:i+width])+"," for i in range(0,len(data),width))

def render(program:bytes,capacity:int=DEFAULT_CAPACITY)->str:
    if program[:4]!=b"ABP1": raise ValueError("program is not an ABP1 image")
    if len(program)>capacity: raise ValueError(f"program exceeds slot capacity ({len(program)} > {capacity})")
    magic=", ".join(f"0x{v:02x}" for v in SLOT_MAGIC)
    digest=", ".join(f"0x{v:02x}" for v in hashlib.sha256(program).digest())
    return f'''/* Generated by tools/abvm_slot.py. Do not edit. */
#include <stddef.h>
#include <stdint.h>
#define ABVM_FLASH_SLOT_CAPACITY {capacity}u
typedef struct AbvmFlashSlot {{
    uint8_t magic[16]; uint32_t version; uint32_t header_size;
    uint32_t capacity; uint32_t program_size; uint8_t program_sha256[32];
    uint8_t program[ABVM_FLASH_SLOT_CAPACITY];
}} AbvmFlashSlot;
_Static_assert(offsetof(AbvmFlashSlot, program) == {SLOT_HEADER_SIZE}u, "ABVM flash slot header layout");
__attribute__((section(".abvm_slot"), aligned(256), used))
const AbvmFlashSlot abvm_flash_slot = {{
    .magic = {{ {magic} }}, .version = {SLOT_VERSION}u,
    .header_size = {SLOT_HEADER_SIZE}u, .capacity = ABVM_FLASH_SLOT_CAPACITY,
    .program_size = {len(program)}u, .program_sha256 = {{ {digest} }},
    .program = {{
{_rows(program)}
    }},
}};
const uint8_t *abvm_program_data(void) {{ return abvm_flash_slot.program; }}
/* The UF2 exporter patches program_size after link. Force a real XIP-flash
 * read so the compiler cannot fold the template program's original size. */
__attribute__((noinline))
size_t abvm_program_size(void) {{
    const volatile uint32_t *program_size = &abvm_flash_slot.program_size;
    return (size_t)*program_size;
}}
'''

def main()->int:
    p=argparse.ArgumentParser(); p.add_argument("program",type=Path); p.add_argument("output",type=Path); p.add_argument("--capacity",type=int,default=DEFAULT_CAPACITY); a=p.parse_args()
    try: source=render(a.program.read_bytes(),a.capacity)
    except ValueError as exc: p.error(str(exc))
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(source,encoding="utf-8"); return 0
if __name__=="__main__": raise SystemExit(main())
