#!/usr/bin/env python3
"""Embed a verified ABP image as a const C array for the initial Pico UF2."""
from __future__ import annotations

import argparse
from pathlib import Path


def render(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return """/* Generated by tools/abvm_embed.py. Do not edit. */
#include <stddef.h>
#include <stdint.h>

const uint8_t abvm_program_image[] = {
%s
};

const size_t abvm_program_image_size = sizeof(abvm_program_image);
""" % "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("program", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    data = args.program.read_bytes()
    if data[:4] != b"ABP1":
        parser.error("program is not an ABP1 image")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(data), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())