#!/usr/bin/env python3
"""Generate the ABVM ABI registry for C#, native firmware, and tooling."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import abvm


ROOT = Path(__file__).resolve().parents[1]


def enum_lines(items: dict[str, int], indent: str = "    ") -> str:
    return "\n".join(f"{indent}{name} = {value}," for name, value in items.items())


def generate() -> dict[Path, str]:
    registry = abvm.abi_registry()
    json_text = json.dumps(registry, indent=2, sort_keys=True) + "\n"

    header = f"""/* Generated by tools/generate_abvm_abi.py. Do not edit. */
#ifndef AMS_ABVM_ABI1_H
#define AMS_ABVM_ABI1_H
#include <stdint.h>

#define ABVM_MAGIC 0x31504241u
#define ABVM_FORMAT_VERSION {registry["formatVersion"]}u
#define ABVM_VM_ABI {registry["vmAbi"]}u
#define ABVM_HEADER_SIZE {registry["sizes"]["header"]}u
#define ABVM_INSTRUCTION_SIZE {registry["sizes"]["instruction"]}u
#define ABVM_ROUTE_SIZE {registry["sizes"]["route"]}u
#define ABVM_RESOURCE_SIZE {registry["sizes"]["resourceCertificate"]}u
#define ABVM_LIMIT_FRAMES {registry["limits"]["frames"]}u
#define ABVM_LIMIT_LANES {registry["limits"]["lanes"]}u
#define ABVM_LIMIT_ACTORS {registry["limits"]["actors"]}u
#define ABVM_LIMIT_EVENTS {registry["limits"]["events"]}u
#define ABVM_LIMIT_INTERRUPTS {registry["limits"]["interrupts"]}u
#define ABVM_LIMIT_SOUND_PROFILES {registry["limits"]["soundProfiles"]}u
#define ABVM_LIMIT_SOUND_LISTENERS {registry["limits"]["soundListeners"]}u
#define ABVM_LIMIT_PWM_CHANNELS {registry["limits"]["pwmChannels"]}u
#define ABVM_LIMIT_PACKAGE_ITEMS {registry["limits"]["packageItems"]}u

typedef enum AbvmOpcode {{
{enum_lines({f"ABVM_OP_{k}": v for k, v in registry["opcodes"].items()})}
}} AbvmOpcode;

typedef enum AbvmConstantKind {{
{enum_lines({f"ABVM_CONST_{k}": v for k, v in registry["constantKinds"].items()})}
}} AbvmConstantKind;

typedef enum AbvmScopePolicy {{
{enum_lines({f"ABVM_SCOPE_{k}": v for k, v in registry["scopePolicies"].items()})}
}} AbvmScopePolicy;

typedef enum AbvmRoutePolicy {{
{enum_lines({f"ABVM_ROUTE_{k}": v for k, v in registry["routePolicies"].items()})}
}} AbvmRoutePolicy;

typedef enum AbvmRouteClockPolicy {{
{enum_lines({f"ABVM_CLOCK_{k}": v for k, v in registry["routeClockPolicies"].items()})}
}} AbvmRouteClockPolicy;

typedef enum AbvmRouteFlag {{
{enum_lines({f"ABVM_ROUTE_FLAG_{k}": v for k, v in registry["routeFlags"].items()})}
}} AbvmRouteFlag;

#pragma pack(push, 1)
typedef struct AbvmHeader {{
    uint32_t magic;
    uint16_t format_version;
    uint16_t vm_abi;
    uint32_t flags, file_size, header_size;
    uint32_t code_offset, code_count;
    uint32_t constant_offset, constant_size;
    uint32_t route_offset, route_count;
    uint32_t resource_offset, resource_size, crc32;
    uint16_t max_frames, max_lanes;
    uint8_t source_sha256[32], program_sha256[32];
    uint32_t reserved;
}} AbvmHeader;

typedef struct AbvmInstruction {{
    uint8_t opcode, flags;
    uint16_t operand_a;
    uint32_t operand_b, operand_c, operand_d;
}} AbvmInstruction;

typedef struct AbvmRoute {{
    uint16_t route_id, policy_flags;
    uint32_t pc, length, name_constant;
}} AbvmRoute;

typedef struct AbvmResourceCertificate {{
    uint16_t version, size, max_frames, max_lanes;
    uint16_t max_actors, max_events, max_interrupts;
    uint16_t sound_profiles, sound_listeners, pwm_channels;
    uint32_t max_constant_bytes, max_type_bytes, max_mouse_bytes;
    uint32_t capabilities;
}} AbvmResourceCertificate;
#pragma pack(pop)

_Static_assert(sizeof(AbvmHeader) == ABVM_HEADER_SIZE, "ABVM header layout");
_Static_assert(sizeof(AbvmInstruction) == ABVM_INSTRUCTION_SIZE,
               "ABVM instruction layout");
_Static_assert(sizeof(AbvmRoute) == ABVM_ROUTE_SIZE, "ABVM route layout");
_Static_assert(sizeof(AbvmResourceCertificate) == ABVM_RESOURCE_SIZE,
               "ABVM resource layout");

#endif
"""

    csharp = f"""// Generated by tools/generate_abvm_abi.py. Do not edit.
using System.Runtime.InteropServices;

namespace Ams.UI.Services;

internal static class AbvmAbi
{{
    public const string Magic = "{registry["magic"]}";
    public const int FormatVersion = {registry["formatVersion"]};
    public const int VmAbi = {registry["vmAbi"]};
    public const int HeaderSize = {registry["sizes"]["header"]};
    public const int InstructionSize = {registry["sizes"]["instruction"]};
    public const int RouteSize = {registry["sizes"]["route"]};
    public const int ResourceCertificateSize =
        {registry["sizes"]["resourceCertificate"]};
}}

internal enum AbvmOpcode : byte
{{
{enum_lines(registry["opcodes"])}
}}

internal enum AbvmConstantKind : byte
{{
{enum_lines(registry["constantKinds"])}
}}

internal enum AbvmScopePolicy : byte
{{
{enum_lines(registry["scopePolicies"])}
}}

internal enum AbvmRoutePolicy : byte
{{
{enum_lines(registry["routePolicies"])}
}}

internal enum AbvmRouteClockPolicy : ushort
{{
{enum_lines(registry["routeClockPolicies"])}
}}

[System.Flags]
internal enum AbvmRouteFlag : ushort
{{
{enum_lines(registry["routeFlags"])}
}}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmHeader
{{
    public uint Magic;
    public ushort FormatVersion;
    public ushort VmAbi;
    public uint Flags;
    public uint FileSize;
    public uint HeaderSize;
    public uint CodeOffset;
    public uint CodeCount;
    public uint ConstantOffset;
    public uint ConstantSize;
    public uint RouteOffset;
    public uint RouteCount;
    public uint ResourceOffset;
    public uint ResourceSize;
    public uint Crc32;
    public ushort MaxFrames;
    public ushort MaxLanes;
    public ulong SourceSha0;
    public ulong SourceSha1;
    public ulong SourceSha2;
    public ulong SourceSha3;
    public ulong ProgramSha0;
    public ulong ProgramSha1;
    public ulong ProgramSha2;
    public ulong ProgramSha3;
    public uint Reserved;
}}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmInstruction
{{
    public byte Opcode;
    public byte Flags;
    public ushort OperandA;
    public uint OperandB;
    public uint OperandC;
    public uint OperandD;
}}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmRoute
{{
    public ushort RouteId;
    public ushort PolicyFlags;
    public uint Pc;
    public uint Length;
    public uint NameConstant;
}}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct AbvmResourceCertificate
{{
    public ushort Version;
    public ushort Size;
    public ushort MaxFrames;
    public ushort MaxLanes;
    public ushort MaxActors;
    public ushort MaxEvents;
    public ushort MaxInterrupts;
    public ushort SoundProfiles;
    public ushort SoundListeners;
    public ushort PwmChannels;
    public uint MaxConstantBytes;
    public uint MaxTypeBytes;
    public uint MaxMouseBytes;
    public uint Capabilities;
}}
"""
    return {
        ROOT / "spec/abvm/abi1.json": json_text,
        ROOT / "firmware/abvm/include/abvm_abi1.h": header,
        ROOT / "ams-shell/src/Ams.UI/Services/AbvmAbi.Generated.cs": csharp,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true",
        help="fail when committed bindings differ from generated output")
    args = parser.parse_args()
    stale = []
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(path.relative_to(ROOT))
    if stale:
        print("stale generated ABVM ABI: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())