#!/usr/bin/env python3
"""Finish PLAN|2 exporter parity: recursive bundles, typed validation, and UI text.

Idempotent migration for the active v0.9.66 branch.  It edits the template source;
tools/make_plan_exporter.py remains the only generator of PlanExporter.cs.
"""
from pathlib import Path
import sys

root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
tpl = root / "tools" / "PlanExporter.cs.tpl"
marker = "PLAN2_BUNDLE_MIGRATION"


def method_span(src: str, signature: str):
    a = src.index(signature)
    b = src.index("{", a)
    depth = 0
    for i in range(b, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return a, i + 1
    raise RuntimeError("unbalanced method: " + signature)


def replace_method(src: str, signature: str, body: str):
    a, b = method_span(src, signature)
    return src[:a] + body.rstrip() + src[b:]


s = tpl.read_text(encoding="utf-8")
if marker not in s:
    s = s.replace("// PLAN2_PARITY_MIGRATION", "// PLAN2_PARITY_MIGRATION\n// " + marker, 1)
    s = s.replace(
        'sb.Append("# generated by Classroom Studio PlanExporter (engine " + EngineVersion + ") from " + sourceName + "\\n");',
        'sb.Append("# generated by Classroom Studio PlanExporter (engine " + EngineVersion + ") from " + Path.GetFileName(sourceName) + "\\n");',
        1,
    )

    bundle_helpers = r'''    private sealed record CompiledBundle(PlanResult Root, IReadOnlyList<(string FileName, string Text)> Children);

    private static AppSettings ChildSettings(AppSettings source) => new()
    {
        PlayRepeatMode = "once",
        MouseMoveSpeedMin = source.MouseMoveSpeedMin,
        MouseMoveSpeedMax = source.MouseMoveSpeedMax,
        TypeKeyMinMs = source.TypeKeyMinMs,
        TypeKeyMaxMs = source.TypeKeyMaxMs,
        KeyboardBoard = source.KeyboardBoard,
    };

    /// <summary>Preflights and compiles every reachable playScript document before the first
    /// destination is touched. Root depth is zero; four included levels are allowed.</summary>
    private static CompiledBundle CompileBundle(IList<StepNode> roots, AppSettings settings,
        int screenW, int screenH, string sourcePath, string machine, string rootOutputName)
    {
        var rootResult = Compile(roots, settings, screenW, screenH, sourcePath, machine);
        var children = new List<(string FileName, string Text)>();
        var errors = new List<string>();
        var completed = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var outputSources = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [rootOutputName] = Path.GetFullPath(sourcePath),
        };
        var active = new List<string> { Path.GetFullPath(sourcePath) };

        void Visit(IList<StepNode> nodes, string ownerPath, int ownerDepth)
        {
            foreach (var node in nodes)
            {
                if (node.IsDisabled) continue;
                if (node.Type == "playScript")
                {
                    var raw = PropEx.GetString(node.Props, "path").Trim();
                    if (raw.Length == 0) { errors.Add("include in " + Path.GetFileName(ownerPath) + ": no .amsj path set"); continue; }
                    var ownerDir = Path.GetDirectoryName(Path.GetFullPath(ownerPath)) ?? ".";
                    var full = Path.GetFullPath(Path.IsPathRooted(raw) ? raw : Path.Combine(ownerDir, raw));
                    if (!File.Exists(full)) { errors.Add("include in " + Path.GetFileName(ownerPath) + ": child not found: " + raw); continue; }
                    if (active.Contains(full, StringComparer.OrdinalIgnoreCase))
                    {
                        errors.Add("include cycle: " + string.Join(" -> ", active.Select(Path.GetFileName).Concat(new[] { Path.GetFileName(full) })));
                        continue;
                    }
                    if (ownerDepth >= 4)
                    {
                        errors.Add("include depth cap 4 exceeded at " + Path.GetFileName(full));
                        continue;
                    }
                    var outputName = Path.GetFileNameWithoutExtension(full) + ".txt";
                    if (outputName.Any(ch => ch < 32 || ch > 126 || "/\\:|%".Contains(ch)))
                    {
                        errors.Add("include output name is unsafe for CIRCUITPY: " + outputName);
                        continue;
                    }
                    if (outputSources.TryGetValue(outputName, out var prior) &&
                        !string.Equals(prior, full, StringComparison.OrdinalIgnoreCase))
                    {
                        errors.Add("duplicate include output '" + outputName + "' from " + prior + " and " + full);
                        continue;
                    }
                    outputSources[outputName] = full;
                    if (completed.Contains(full)) continue; // same source may be referenced more than once; emit once

                    List<StepNode> childSteps;
                    try { childSteps = DocumentService.Load(full); }
                    catch (Exception ex) { errors.Add("include '" + raw + "' is not a valid .amsj: " + ex.Message); continue; }

                    PlanResult childResult;
                    try { childResult = Compile(childSteps, ChildSettings(settings), screenW, screenH, full, machine); }
                    catch (PlanBlockedException bx)
                    {
                        errors.AddRange(bx.Errors.Select(e => "include " + Path.GetFileName(full) + ": " + e));
                        continue;
                    }
                    children.Add((outputName, childResult.Text));
                    active.Add(full);
                    Visit(childSteps, full, ownerDepth + 1);
                    active.RemoveAt(active.Count - 1);
                    completed.Add(full);
                }
                Visit(node.Children, ownerPath, ownerDepth);
            }
        }

        Visit(roots, sourcePath, 0);
        if (errors.Count > 0) throw new PlanBlockedException(errors);
        return new CompiledBundle(rootResult, children);
    }

'''
    export_signature = "    public static IReadOnlyList<string> Export("
    s = s.replace(export_signature, bundle_helpers + export_signature, 1)

    export_method = r'''    public static IReadOnlyList<string> Export(string planPath, IList<StepNode> steps,
        AppSettings settings, int screenW, int screenH, string sourceName, string machine)
    {
        var full = Path.GetFullPath(planPath);
        var dir = Path.GetDirectoryName(full);
        if (string.IsNullOrEmpty(dir)) throw new IOException("cannot resolve the folder of " + planPath);
        var bundle = CompileBundle(steps, settings, screenW, screenH, sourceName, machine, Path.GetFileName(full));
        var enginePath = Path.Combine(dir, "plan_engine.py");
        var readmePath = Path.Combine(dir, "README-PLAN.md");
        var payloads = new List<(string Path, string Text)> { (full, bundle.Root.Text) };
        payloads.AddRange(bundle.Children.Select(c => (Path.Combine(dir, c.FileName), c.Text)));
        payloads.Add((enginePath, BuildEnginePy()));
        payloads.Add((readmePath, BuildReadme(bundle.Root, Path.GetFileName(sourceName), machine)));

        var tx = Guid.NewGuid().ToString("N");
        var temps = payloads.Select(p => p.Path + "." + tx + ".tmp").ToArray();
        var backups = payloads.Select(p => p.Path + "." + tx + ".bak").ToArray();
        var published = new List<int>();
        try
        {
            // No destination is touched until every root/child/engine/readme payload is staged.
            for (int i = 0; i < payloads.Count; i++)
                File.WriteAllText(temps[i], payloads[i].Text, new UTF8Encoding(false));
            for (int i = 0; i < payloads.Count; i++)
            {
                if (File.Exists(payloads[i].Path)) File.Move(payloads[i].Path, backups[i]);
                File.Move(temps[i], payloads[i].Path);
                published.Add(i);
            }
            foreach (var b in backups) if (File.Exists(b)) File.Delete(b);
            return payloads.Select(p => p.Path).ToList();
        }
        catch
        {
            // Restore every prior file, including a backup made just before the failing move.
            foreach (var i in published.AsEnumerable().Reverse())
                if (File.Exists(payloads[i].Path)) File.Delete(payloads[i].Path);
            for (int i = 0; i < payloads.Count; i++)
                if (File.Exists(backups[i])) File.Move(backups[i], payloads[i].Path, true);
            throw;
        }
        finally
        {
            foreach (var p in temps.Concat(backups))
                if (File.Exists(p)) File.Delete(p);
        }
    }'''
    s = replace_method(s, export_signature, export_method)

    validator = r'''    private static void ValidatePlan(string text)
    {
        var stack = new List<(string Kind, bool ElseSeen, int Line)>();
        var labels = new HashSet<string>(StringComparer.Ordinal);
        var gotos = new List<string>();
        var known = new HashSet<string>{"PLAN","SCREEN","SPEED","DELAY","LOOP","LOOPTIME","ENDLOOP","RMOUSE","MOVETO","CLICK","TYPE","WLIGHT","WSND","TRGSND","IFSND","IFLUX","ELSE","ENDIF","KEY","KDOWN","KUP","WHEEL","LABEL","GOTO","RAW","RPKG","PKGITEM","ENDPKG","PGROUP","PARITEM","ENDPAR","INCLUDE","BEEP"};
        bool first = true;
        string previousOp = "";
        var lines = text.Split('\n');
        for (int li = 0; li < lines.Length; li++)
        {
            var line = lines[li].Trim();
            if (line.Length == 0 || line.StartsWith('#')) continue;
            var fields = line.Split('|');
            var op = fields[0];
            void Bad(string why) => throw new PlanBlockedException(new[] { "PlanExporter BUG: line " + (li + 1) + ": " + why + " (please report)" });
            void Need(string kind, string closer)
            {
                if (stack.Count == 0 || stack[^1].Kind != kind)
                    Bad(closer + " cannot close " + (stack.Count == 0 ? "the root" : stack[^1].Kind));
            }

            if (!known.Contains(op)) Bad("unknown op '" + op + "'");
            if (first && (op != "PLAN" || fields.Length < 2 || fields[1] != "2")) Bad("PLAN must be first with version 2");
            if (op == "PLAN" && !first) Bad("duplicate/non-first PLAN");

            switch (op)
            {
                case "LOOP": case "LOOPTIME": stack.Add(("LOOP", false, li + 1)); break;
                case "IFSND": case "IFLUX": stack.Add(("IF", false, li + 1)); break;
                case "RPKG": stack.Add(("RPKG", false, li + 1)); break;
                case "PGROUP": stack.Add(("PGROUP", false, li + 1)); break;
                case "ENDLOOP": Need("LOOP", op); stack.RemoveAt(stack.Count - 1); break;
                case "ELSE":
                    Need("IF", op);
                    if (stack[^1].ElseSeen) Bad("duplicate ELSE in one IF block");
                    stack[^1] = ("IF", true, stack[^1].Line);
                    break;
                case "ENDIF": Need("IF", op); stack.RemoveAt(stack.Count - 1); break;
                case "PKGITEM":
                    Need("RPKG", op);
                    if (previousOp is "RPKG" or "PKGITEM") Bad("empty Random Package item");
                    break;
                case "ENDPKG":
                    Need("RPKG", op);
                    if (previousOp is "RPKG" or "PKGITEM") Bad("empty Random Package item");
                    stack.RemoveAt(stack.Count - 1);
                    break;
                case "PARITEM":
                    Need("PGROUP", op);
                    if (previousOp is "PGROUP" or "PARITEM") Bad("empty Parallel Group branch");
                    break;
                case "ENDPAR":
                    Need("PGROUP", op);
                    if (previousOp is "PGROUP" or "PARITEM") Bad("empty Parallel Group branch");
                    stack.RemoveAt(stack.Count - 1);
                    break;
            }

            if (op == "LABEL")
            {
                if (fields.Length < 2 || fields[1].Length == 0 || !labels.Add(fields[1])) Bad("bad/duplicate LABEL");
            }
            if (op == "GOTO")
            {
                if (fields.Length < 2 || fields[1].Length == 0) Bad("empty GOTO");
                gotos.Add(fields[1]);
            }
            if (op == "INCLUDE" && (!HasKv(fields, "file", out var file) || file.Length == 0 ||
                file.Any(ch => ch < 32 || ch > 126 || "/\\:|%".Contains(ch)))) Bad("unsafe INCLUDE filename");
            first = false;
            previousOp = op;
        }
        if (stack.Count > 0)
            throw new PlanBlockedException(new[] { "PlanExporter BUG: line " + stack[^1].Line + ": unclosed " + stack[^1].Kind + " container (please report)" });
        foreach (var target in gotos)
            if (!labels.Contains(target)) throw new PlanBlockedException(new[] { "PlanExporter BUG: GOTO target '" + target + "' is undefined (please report)" });
    }'''
    s = replace_method(s, "    private static void ValidatePlan(", validator)

    s = s.replace("Writes plan.txt (the compiled plan), plan_engine.py", "Writes plan.txt, every recursively compiled child plan, plan_engine.py", 1)
    s = s.replace("این سه فایل را روی درایو CIRCUITPY کپی کن", "همه‌ی فایل‌های این bundle را روی درایو CIRCUITPY کپی کن", 1)
    s = s.replace("- plan.txt ← پلن کامپایل‌شده (همین فایل)\\n", "- plan.txt ← پلن اصلی؛ فایل‌های *.txt دیگر ← playScriptهای کامپایل‌شده\\n", 1)
    tpl.write_text(s, encoding="utf-8", newline="\n")
    print("PLAN2 recursive-bundle migration applied")
else:
    print("PLAN2 recursive-bundle migration already applied")

# Keep the checked-in UI payload/source and the legacy wiring patcher on this same contract.
for rel in [
    "tools/plan_exporter_vm_command.cs.inc",
    "ams-shell/src/Ams.UI/ViewModels/MainViewModel.cs",
    "ams-shell/src/Ams.UI/MainWindow.xaml",
    "tools/patch_plan_exporter_ui.py",
]:
    p = root / rel
    if not p.exists():
        continue
    t = p.read_text(encoding="utf-8")
    t = t.replace("PLAN|1, the gen-1 engine of firmware 0.9.64b", "PLAN|2, engine 0.9.66")
    t = t.replace("روی PLAN|1 پشتیبانی نمی‌شود", "روی PLAN|2 پشتیبانی نمی‌شود")
    t = t.replace('_currentFile is null ? "untitled" : Path.GetFileName(_currentFile)', '_currentFile ?? "untitled"')
    t = t.replace("copy plan.txt + plan_engine.py onto CIRCUITPY", "copy every generated *.txt plan + plan_engine.py onto CIRCUITPY")
    t = t.replace("plan.txt و plan_engine.py را در ریشه‌ی CIRCUITPY کپی کن", "همه‌ی فایل‌های *.txt و plan_engine.py را در ریشه‌ی CIRCUITPY کپی کن")
    t = t.replace("موتور gen-1 فریم‌ور 0.9.64b", "bundle بازگشتی PLAN|2 فریم‌ور 0.9.66")
    t = t.replace("59 pins the PLAN|1 contract", "59 pins the PLAN|2 recursive-bundle contract")
    t = t.replace("v0.9.65 wiring patcher", "v0.9.66 PLAN|2 wiring patcher")
    if rel.endswith("patch_plan_exporter_ui.py"):
        if "PLAN2_BUNDLE_PATCHER" not in t:
            t = t.replace("import pathlib\nimport sys", "import pathlib\nimport subprocess\nimport sys\n\n# PLAN2_BUNDLE_PATCHER", 1)
        if "PLAN2_MIGRATION_CHAIN" not in t:
            chain = '''# PLAN2_MIGRATION_CHAIN — one legacy patch command now deterministically reaches the current sources.\nfor script in (\n    "upgrade_plan_exporter_plan2.py",\n    "upgrade_plan_exporter_tests_plan2.py",\n    "upgrade_plan_exporter_bundle.py",\n    "upgrade_plan_exporter_bundle_tests.py",\n    "make_plan_exporter.py",\n    "sync_plan_exporter_tests.py",\n):\n    result = subprocess.run([sys.executable, str(ROOT / "tools" / script), str(ROOT)])\n    if result.returncode != 0:\n        raise SystemExit(result.returncode)\n\n'''
            t = t.replace("# -- post-conditions", chain + "# -- post-conditions", 1)
    p.write_text(t, encoding="utf-8", newline="\n")
